import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {emptyBroker,type Broker,type Line,type Review,type Shipment} from '../shared/model.js';
import './style.css';
type Result=Review&{sessionId:string};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
function download(name:string,content:string,type='application/xml'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const brokerFields:[keyof Broker,string,string][]=[['importerTaxId','Importer tax ID','Tax ID in NetCHB profile'],['consigneeName','Ultimate consignee','Confirm customs party'],['consigneeTaxId','Consignee tax ID','Tax ID in partner profile'],['processingPort','Processing port','4-digit CBP code'],['entryPort','Entry port','4-digit CBP code'],['entryType','Entry type','2-digit code'],['entryDate','Entry date','YYYY-MM-DD'],['arrivalDate','Actual arrival date','YYYY-MM-DD'],['mode','Transport mode','2-digit mode code'],['bondType','Bond type','00, 08 or 09'],['suretyCode','Surety code','3-digit code'],['paymentType','Payment type','1–8'],['firmsCode','FIRMS location','4-character code'],['relatedParty','Related parties','Y or N']];

function App(){
 const [files,setFiles]=useState<File[]>([]);const [result,setResult]=useState<Result|null>(null);const [shipment,setShipment]=useState<Shipment|null>(null);const [broker,setBroker]=useState<Broker>(emptyBroker());
 const [tab,setTab]=useState('review');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [config,setConfig]=useState<{engine:string;model:string|null}|null>(null);const [dirty,setDirty]=useState(false);const [json,setJson]=useState('');const [advanced,setAdvanced]=useState(false);const [copied,setCopied]=useState(false);
 const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(setConfig).catch(()=>setError('Backend unavailable. Start the server and reload.'));},[]);
 async function request(url:string,options:RequestInit){setBusy(true);setError('');try{const r=await fetch(url,options);const body=await r.json();if(!r.ok)throw new Error([body.error,...body.details??[]].join('\n'));setResult(body);setShipment(body.shipment);setBroker(body.broker);setJson(JSON.stringify({fields:body.shipment.fields,lines:body.shipment.lines},null,2));setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
 function upload(){const data=new FormData();files.forEach(f=>data.append('documents',f));void request('/api/shipments',{method:'POST',body:data});}
 function regenerate(nextShipment=shipment,nextBroker=broker){if(result&&nextShipment)void request('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:result.sessionId,shipment:nextShipment,broker:nextBroker})});}
 function editLine(id:string,key:keyof Line,value:string){if(!shipment)return;const numeric=['quantity','unitPrice','amount','assist','customsValue','cartons','netWeight','grossWeight','quantity1','quantity2'].includes(key);const next={...shipment,lines:shipment.lines.map(l=>l.id===id?{...l,[key]:numeric?(value===''?null:Number(value)):value}:l)};setShipment(next);setDirty(true);}
 function resolve(id:string,note:string){const next={...broker,confirmations:{...broker.confirmations,[id]:note}};setBroker(next);regenerate(shipment,next);}
 const unresolved=result?.issues.filter(i=>!i.resolved).length??0;const blockers=result?.issues.filter(i=>i.severity==='blocker').length??0;
 return <div className="shell">
  <aside><a className="brand" href="/"> <span className="brand-mark">e</span> entry desk<span className="beta">BETA</span></a><div className="workspace-label">SHIPMENT WORKSPACE</div><button className="nav selected" onClick={()=>setTab('review')}>▦ <span>Entry preparation</span><span className="nav-dot"/></button><div className="aside-note"><span className="small-cap">A CLEAR PATH TO FILING</span><p>From shipping documents<br/>to a reviewed entry.</p><div className="mini-line"/></div><div className="aside-bottom"><span className="status-dot"/> {config?.engine==='ai'?'AI-assisted extraction':'Local extraction'}<small>{config?.model??'PDF text + OCR'}<br/>No customs transmission</small></div></aside>
  <main><header><div className="crumb">Workspace <span>/</span> Entry preparation</div><span className="header-tag">NETCHB XML</span></header>
  <div className="content"><div className="heading"><div><div className="eyebrow">DOCUMENTS IN. CLARITY OUT.</div><h1>Prepare your next entry.</h1><p>Extract the shipment. Resolve the gaps. Export the XML.</p></div><div className="step-pill">01 <span>Prepare & review</span></div></div>
  {error&&<div role="alert" className="error">{error}</div>}
  <section className="upload-card"><div className="section-heading"><h2>Shipment documents</h2><span className="muted">Invoice · Packing list · Bill of lading</span></div><div className="upload-body"><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFiles([...e.dataTransfer.files].filter(f=>/\.pdf$/i.test(f.name)));}}><span className="upload-icon">↥</span><div><strong>{files.length?`${files.length} documents selected`:'Drop your shipment PDFs here'}</strong><p>Up to 6 files · 20 MB per file · Scanned PDFs supported</p></div><button className="secondary" onClick={()=>input.current?.click()} disabled={busy}>Browse files</button><input ref={input} type="file" accept="application/pdf,.pdf" multiple hidden onChange={e=>setFiles([...e.target.files??[]])}/></div>{files.length>0&&<div className="file-chips">{files.map((f,i)=><span key={f.name+i}>▤ {f.name}<button aria-label={`Remove ${f.name}`} onClick={()=>setFiles(files.filter((_,n)=>n!==i))}>×</button></span>)}</div>}<div className="upload-footer"><span>{config?.engine==='ai'?'Document text is sent to your configured AI provider.':'Documents are processed locally. Review unfamiliar layouts carefully.'}</span><button className="primary" disabled={!files.length||busy} onClick={upload}>{busy?'Processing…':'Prepare entry'} <span>↗</span></button></div></div></section>
  {!result&&<div className="example-row"><span>Explore the supplied shipment, including explicit visual transcription corrections.</span><button className="text-button" disabled={busy} onClick={()=>request('/api/example',{method:'POST'})}>Open reviewed example ↗</button></div>}
  {busy&&<div role="status" className="processing"><span className="spinner"/> Reading pages, checking shipment facts and validating XML. Scanned documents may take a minute.</div>}
  {result&&shipment?<>
   <div className="result-heading"><div><span className="small-cap">CURRENT SHIPMENT</span><h2>{String(shipment.fields.invoiceNo??'Shipment review')}</h2><p>{String(shipment.fields.buyer??'Buyer not established')} <span>·</span> {String(shipment.fields.portDischarge??'Destination to confirm')}</p></div><span className={'readiness '+(result.ready&&!dirty?'ready':'')}>{dirty?'Unsaved changes':result.ready?'Reviewed export ready':`${unresolved} items need attention`}</span></div>
   <div className="stats"><div><span>Proposed customs value</span><strong>{money(result.totals.proposedValue)}</strong><small>Includes assists and declared samples</small></div><div><span>Invoice lines</span><strong>{shipment.lines.length.toString().padStart(2,'0')}</strong><small>{result.documents.length} source documents</small></div><div><span>Manifest packages</span><strong>{String(shipment.fields.packages??'—')}</strong><small>{shipment.fields.grossWeight??'—'} kg selected gross weight</small></div><div><span>Filing blockers</span><strong className="amber">{blockers.toString().padStart(2,'0')}</strong><small>Supply broker-confirmed information</small></div></div>
   <div className="tabs"><div>{[['review','Review & complete'],['lines','Shipment data'],['xml','Entry XML'],['sources','Source evidence']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='review'&&<span>{unresolved}</span>}</button>)}</div><button className="primary compact" disabled={busy} onClick={()=>regenerate()}>{dirty?'Save & regenerate':'Recheck entry'} ↗</button></div>
   {dirty&&<div className="notice">Save and regenerate to update the XML, totals, and review items. Data edits invalidate prior review notes.</div>}
   {tab==='review'&&<div className="review-grid"><section className="panel"><div className="panel-title"><h2>Complete the entry</h2><span className="muted">Broker information</span></div><p className="panel-intro">These values depend on the filing account and actual shipment. Enter confirmed information.</p><div className="form-grid">{brokerFields.map(([key,label,placeholder])=><label key={key}>{label}<input value={String(broker[key]??'')} placeholder={placeholder} onChange={e=>{setBroker({...broker,[key]:e.target.value});setDirty(true);}}/></label>)}<label>USD per invoice currency<input type="number" min="0" step="any" placeholder="Only for non-USD invoices" value={broker.exchangeRate??''} onChange={e=>{setBroker({...broker,exchangeRate:e.target.value?Number(e.target.value):null});setDirty(true);}}/></label></div><button className="primary full" disabled={busy} onClick={()=>regenerate()}>Save & regenerate XML ↗</button></section><section className="panel"><div className="panel-title"><h2>Review queue</h2><span className="count">{unresolved} open</span></div><p className="panel-intro">Fix missing fields in the editors. Record an evidence-based decision for each discrepancy.</p><div className="issue-list">{result.issues.map(issue=><IssueCard key={issue.id} issue={issue} disabled={busy||dirty} onResolve={resolve}/>)}</div></section></div>}
   {tab==='lines'&&<section className="panel"><div className="panel-title"><h2>Extracted shipment data</h2><button className="secondary" onClick={()=>{setJson(JSON.stringify({fields:shipment.fields,lines:shipment.lines},null,2));setAdvanced(!advanced);}}>Full shipment editor</button></div><p className="panel-intro">Printed invoice values are preserved. Confirm each classification, manufacturer and statistical quantity.</p><div className="table-scroll"><table><thead><tr><th>Style / description</th><th>Origin</th><th>Quantity</th><th>Amount</th><th>Assist</th><th>Customs sample value</th><th>10-digit HTS</th><th>Manufacturer ID</th><th>Stat. qty 1</th><th>Unit 1</th><th>Stat. qty 2</th><th>Unit 2</th></tr></thead><tbody>{shipment.lines.map(l=><tr key={l.id}><td><strong>{l.style}</strong><small>{l.description}</small><small>{l.composition}</small></td>{(['origin','quantity','amount','assist','customsValue','hts','manufacturerId','quantity1','uom1','quantity2','uom2'] as (keyof Line)[]).map(k=><td key={k}><input aria-label={`${l.style} ${k}`} className={['hts','manufacturerId'].includes(k)?'wide':''} value={String(l[k]??'')} onChange={e=>editLine(l.id,k,e.target.value)}/></td>)}</tr>)}</tbody></table></div>{advanced&&<div className="advanced"><p>Edit transport fields, prices, weights, manufacturer names, or add invoice lines here. Keep line IDs unique. Evidence stays attached to the original source.</p><textarea aria-label="Shipment JSON" value={json} onChange={e=>setJson(e.target.value)} spellCheck={false}/><button className="primary" onClick={()=>{try{const edited=JSON.parse(json);const next={...shipment,...edited,evidence:shipment.evidence};setShipment(next);setDirty(true);regenerate(next);}catch(e){setError('Invalid JSON: '+String(e));}}}>Apply & validate</button></div>}</section>}
   {tab==='xml'&&<section className="panel xml-panel"><div className="panel-title"><h2>NetCHB entry XML</h2><span className={'schema-status '+(result.schema.valid?'valid':'')}>{result.schema.valid===true?'XSD valid':result.schema.valid===null?'Validation unavailable':'XSD incomplete / invalid'}</span></div><p className="panel-intro">{result.ready?'Reviewed export: final NetCHB and CBP acceptance require the broker’s filing account.':'Draft export: unresolved information is omitted. Schema validity alone does not establish filing readiness.'}</p><div className="xml-actions"><button className="secondary" disabled={dirty} onClick={()=>{navigator.clipboard.writeText(result.xml).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000);}).catch(()=>setError('Clipboard unavailable. Download the XML instead.'));}}>{copied?'Copied':'Copy XML'}</button><button className="primary" disabled={dirty} onClick={()=>download(result.ready?'entry.xml':'entry.draft.xml',result.xml)}>Download {result.ready?'entry':'draft'} ↓</button><button className="secondary" disabled={dirty} onClick={()=>download('review-report.json',JSON.stringify(result,null,2),'application/json')}>Export review report</button></div>{result.schema.errors.map((e,i)=><pre key={i} className="schema-errors">{e}</pre>)}<pre className="xml-code"><code>{result.xml}</code></pre></section>}
   {tab==='sources'&&<section className="panel"><div className="panel-title"><h2>Every page, with its evidence</h2><span className="muted">{result.documents.length} documents</span></div><p className="panel-intro">Compare these extracted quotes with the original PDFs. OCR can miss handwritten corrections; rules can miss unfamiliar tables.</p>{result.documents.map(d=><div className="source" key={d.id}><h3>▤ {d.name}<span>{d.kind} · {d.engine}</span></h3>{d.warnings.map((w,i)=><p className="source-warning" key={i}>{w}</p>)}{d.pages.map(p=><details key={p.page}><summary>Page {p.page} <span>{p.method==='ocr'?'OCR scan':'Embedded text'}</span></summary><pre>{p.text}</pre></details>)}</div>)}</section>}
  </>:<div className="empty-state"><div className="empty-symbol">▤</div><h2>Your shipment starts here.</h2><p>Upload the documents to see extracted facts, a review checklist,<br/>and XML built against NetCHB’s published schema.</p><div className="empty-steps"><span><b>1</b> Upload PDFs</span><i>→</i><span><b>2</b> Review the gaps</span><i>→</i><span><b>3</b> Export entry XML</span></div></div>}
  <footer>Entry Desk <span>·</span> NetCHB schema-backed preparation <a href="https://www.netchb.com/xml/entry/entry.xsd" target="_blank" rel="noreferrer">View entry schema ↗</a></footer></div></main></div>;
}
function IssueCard({issue,disabled,onResolve}:{issue:Review['issues'][number];disabled:boolean;onResolve:(id:string,note:string)=>void}){
 const [note,setNote]=useState(issue.note??'');return <details className={'issue '+issue.severity+(issue.resolved?' resolved':'')} open={issue.resolved?false:undefined}><summary><span className="issue-indicator">{issue.resolved?'✓':issue.severity==='blocker'?'!':'↗'}</span><strong>{issue.title}</strong><span className="issue-tag">{issue.resolved?'Reviewed':issue.severity==='blocker'?'Required':'Review'}</span></summary><div className="issue-detail"><p>{issue.detail}</p>{issue.evidence.map((e,i)=><blockquote key={i}><p>“{e.quote}”</p><cite>{e.document} · page {e.page} · extracted: {String(e.value)}</cite></blockquote>)}{issue.severity==='review'&&<><label>Decision and supporting evidence<textarea placeholder="Describe the confirmed decision and its supporting evidence…" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="secondary" disabled={disabled||note.trim().length<10} onClick={()=>onResolve(issue.id,note.trim())}>Record review</button>{issue.resolved&&<button className="text-button" disabled={disabled} onClick={()=>onResolve(issue.id,'')}>Reopen</button>}</>}</div></details>;
}
createRoot(document.getElementById('root')!).render(<App/>);
